### ISSUE TITLE
Can't read app/src/main/java/com/hapirobo/shortcut_template/MainActivity.java: No such file or directory

### ISSUE THREAD

**Issue by KishanNagi** [ray-hrst/temi-shortcut#1]
Hi, 

I am stuck with this issue. I have the Android SDK installed and working and the ANDROID_HOME environment variable is also properly set.

It fails when I do  -  ./shortcut.sh <...> <...>.

Your help would be greatly appreciated.

Thanks & Cheers
Kishan

**Comment by r-oung** [comment]
@KishanNagi What exactly fails? Could you please attach your console output?

**Comment by KishanNagi** [comment]
Hi Ray,

I have attached the output. Please let me know if there's anything more I can provide you.
![temi1](https://user-images.githubusercontent.com/41316318/76372882-f3824f80-6392-11ea-8ede-1166506dd50a.png)
![temi2](https://user-images.githubusercontent.com/41316318/76372889-fa10c700-6392-11ea-9d63-8a0cbcfea64e.png)

**Comment by r-oung** [comment]
@KishanNagi your console output doesn't look right to me. Are you using the latest version? In the `temi-shortcut` directory, try:
```
git pull
git submodule update
```
and try again. If that doesn't work, please run `git status` in the command line and send me the output.

**Comment by r-oung** [comment]
@KishanNagi did this fix your issue?

**Comment by KishanNagi** [comment]
Hi,

I could not get back to it since I have been sick and not working for
sometime.

I will get back to you once I start working again.


Thanks
Kishan

**Comment by KishanNagi** [comment]
Hi,

The same issue persists. Please find attached the output of git status. 

![1_ray](https://user-images.githubusercontent.com/41316318/77596709-e0ee4580-6f50-11ea-839c-691f34b71de9.png)
![2_ray](https://user-images.githubusercontent.com/41316318/77596711-e21f7280-6f50-11ea-9e38-abc295936ceb.png)

**Comment by r-oung** [comment]
@KishanNagi I think I see the problem. Try deleting the `tmp/` directory and run the script again. The script will fail like this if there's already a `tmp/` folder in the directory.

**Comment by r-oung** [comment]
I've updated the repository to avoid having to remove the `tmp/` directory. Remember to update the submodules when you pull. I hope this fixes your problem.

**Comment by KishanNagi** [comment]
Hi @ray-hrst,

Appreciate your help. However, I am running into this new issue now. 
 
![1](https://user-images.githubusercontent.com/41316318/79529069-11885180-80af-11ea-8985-94cd27fb9f39.png)

**Comment by r-oung** [comment]
@KishanNagi this isn't really an issue with the script, but an issue with accepting Android SDK licenses, see here: https://stackoverflow.com/a/55641042.

From the command line, try:
```
export JAVA_HOME=/path/to/android-studio/jre/
/path/to/Android/Sdk/tools/bin/sdkmanager --licenses
```

and accept (`yes`) the license(s). Then run the script again.
